package utils

import (
	"encoding/json"
	"testing"
)

var mappingStr = `{
    "settings":{
        "index":{
            "number_of_shards":"5",
            "max_result_window":"2000000",
            "analysis":{
                "analyzer":{
                    "fofa_dot_analyzer":{
                        "type":"custom",
                        "char_filter":[
                            "fofa_dot_to_space"
                        ],
                        "tokenizer":"fofa_dot_tokenizer"
                    }
                },
                "char_filter":{
                    "fofa_dot_to_space":{
                        "pattern":"[.:/]",
                        "type":"pattern_replace",
                        "replacement":" "
                    }
                },
                "tokenizer":{
                    "fofa_dot_tokenizer":{
                        "type":"whitespace"
                    }
                }
            },
            "number_of_replicas":"1"
        }
    },
    "mappings":{
        "properties":{
            "structinfo":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "jarm":{
                "properties":{
                    "hash":{
                        "type":"keyword"
                    },
                    "group":{
                        "type":"keyword"
                    }
                }
            },
            "ipcnet":{
                "type":"ip"
            },
            "shash":{
                "type":"keyword"
            },
            "ban_len":{
                "type":"integer"
            },
            "appserver":{
                "type":"keyword"
            },
            "cert":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "language":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "owners":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "protocol":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "lastchecktime":{
                "format":"yyyy-MM-dd HH:mm:ss",
                "type":"date"
            },
            "host":{
                "analyzer":"fofa_dot_analyzer",
                "type":"text",
                "fields":{
                    "host_raw":{
                        "type":"keyword"
                    }
                }
            },
            "parent_category":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "id":{
                "type":"long"
            },
            "text":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "is_local":{
                "type":"boolean"
            },
            "lastupdatetime":{
                "format":"yyyy-MM-dd HH:mm:ss",
                "type":"date"
            },
            "ip":{
                "type":"ip",
                "fields":{
                    "ip_raw":{
                        "type":"keyword"
                    },
                    "ipstr":{
                        "analyzer":"fofa_dot_analyzer",
                        "type":"text"
                    }
                }
            },
            "hostnames":{
                "type":"keyword"
            },
            "version":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "tags":{
                "type":"keyword"
            },
            "rule_tags":{
                "type":"nested",
                "properties":{
                    "product":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "category_code":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            },
                            "keyword":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "level":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "softhard":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "cn_parent_category":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "cn_company":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "tags":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            },
                            "keyword":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "tags_code":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            },
                            "keyword":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "cn_product":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "rule_id":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "categories_code":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "cn_category":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "parent_category":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "company":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "category":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":256,
                                "type":"keyword"
                            }
                        }
                    },
                    "nation":{
                        "type":"keyword"
                    },
                    "brand":{
                        "type":"keyword"
                    },
                    "version":{
                        "type":"keyword"
                    },
                    "model":{
                        "type":"keyword"
                    },
                    "score":{
                        "type":"integer"
                    }
                }
            },
            "dbs":{
                "properties":{
                    "DbSize":{
                        "type":"long"
                    },
                    "Count":{
                        "type":"long"
                    },
                    "Records":{
                        "type":"long"
                    }
                }
            },
            "field":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "port":{
                "type":"integer",
                "fields":{
                    "port_raw":{
                        "type":"keyword"
                    }
                }
            },
            "domain":{
                "type":"keyword"
            },
            "subdomain":{
                "type":"keyword"
            },
            "fhash":{
                "type":"keyword"
            },
            "ipip":{
                "properties":{
                    "country":{
                        "type":"keyword"
                    },
                    "currency_name":{
                        "type":"keyword"
                    },
                    "base_station":{
                        "type":"keyword"
                    },
                    "city":{
                        "type":"keyword"
                    },
                    "timezone":{
                        "type":"keyword"
                    },
                    "isp":{
                        "type":"keyword"
                    },
                    "city_code":{
                        "type":"keyword"
                    },
                    "continent_code":{
                        "type":"keyword"
                    },
                    "idc":{
                        "type":"keyword"
                    },
                    "currency_code":{
                        "type":"keyword"
                    },
                    "timezone2":{
                        "type":"keyword"
                    },
                    "province":{
                        "type":"keyword"
                    },
                    "organization":{
                        "type":"keyword"
                    },
                    "country_code2":{
                        "type":"keyword"
                    },
                    "country_code3":{
                        "type":"keyword"
                    },
                    "location":{
                        "type":"geo_point"
                    },
                    "phone_prefix":{
                        "type":"keyword"
                    }
                }
            },
            "job_type":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "server":{
                "type":"text",
                "fields":{
                    "server_raw":{
                        "type":"keyword"
                    }
                }
            },
            "nhash":{
                "type":"keyword"
            },
            "status_code":{
                "type":"long"
            },
            "notretry":{
                "type":"boolean"
            },
            "industry":{
                "type":"keyword"
            },
            "is_ipv6":{
                "type":"boolean"
            },
            "is_honeypot":{
                "type":"boolean"
            },
            "isdomain":{
                "type":"boolean"
            },
            "is_sensitive":{
                "type":"boolean"
            },
            "company":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "base_protocol":{
                "type":"keyword"
            },
            "middleware":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "sensitive_word":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "product":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "geoip":{
                "dynamic":"true",
                "properties":{
                    "request":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "timezone":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "area_code":{
                        "type":"long"
                    },
                    "ip":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "latitude":{
                        "type":"double"
                    },
                    "continent_code":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "city_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "country_code2":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "country_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "dma_code":{
                        "type":"long"
                    },
                    "country_code3":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "location":{
                        "type":"geo_point"
                    },
                    "region_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "real_region_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "postal_code":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "longitude":{
                        "type":"double"
                    },
                    "isp":{
                        "type":"keyword"
                    },
                    "asnnumber":{
                        "type":"keyword"
                    },
                    "owner":{
                        "type":"keyword"
                    },
                    "radius":{
                        "type":"keyword"
                    },
                    "scene":{
                        "type":"keyword"
                    }
                }
            },
            "os":{
                "type":"keyword"
            },
            "banner":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "serial_number":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "certs":{
                "dynamic":"true",
                "properties":{
                    "issuer_cn":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "subject_org":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "subject_cns":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "cert_date":{
                        "format":"yyyy-MM-dd HH:mm:ss",
                        "type":"date"
                    },
                    "not_before":{
                        "format":"yyyy-MM-dd HH:mm:ss",
                        "type":"date"
                    },
                    "issuer_cns":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "cert_num":{
                        "type":"integer"
                    },
                    "sig_alth":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "not_after":{
                        "format":"yyyy-MM-dd HH:mm:ss",
                        "type":"date"
                    },
                    "subject_cn":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "issuer_org":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "v":{
                        "type":"keyword"
                    },
                    "valid_type":{
                        "type":"keyword"
                    },
                    "domain":{
                        "type":"text",
                        "fields":{
                            "raw":{
                                "type":"keyword"
                            }
                        }
                    },
                    "is_valid":{
                        "type":"boolean"
                    },
                    "sn":{
                        "type":"keyword"
                    }
                }
            },
            "c_other_tags":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "v":{
                "type":"long"
            },
            "time":{
                "type":"date"
            },
            "category":{
                "type":"text",
                "fields":{
                    "keyword":{
                        "ignore_above":256,
                        "type":"keyword"
                    }
                }
            },
            "geoip2":{
                "dynamic":"true",
                "properties":{
                    "country":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "currency_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "base_station":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "city":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "timezone":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "isp":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "city_code":{
                        "type":"keyword"
                    },
                    "continent_code":{
                        "ignore_above":32765,
                        "type":"keyword"
                    },
                    "idc":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "currency_code":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "timezone2":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "province":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "organization":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "country_code2":{
                        "type":"keyword"
                    },
                    "country_code3":{
                        "type":"keyword"
                    },
                    "location":{
                        "type":"geo_point"
                    },
                    "phone_prefix":{
                        "type":"keyword"
                    }
                }
            },
            "asn":{
                "properties":{
                    "as_number":{
                        "type":"long"
                    },
                    "as_organization":{
                        "type":"keyword"
                    }
                }
            },
            "geoip3":{
                "dynamic":"true",
                "properties":{
                    "timezone":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "area_code":{
                        "type":"long"
                    },
                    "isp":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "latitude":{
                        "type":"double"
                    },
                    "continent_code":{
                        "ignore_above":32765,
                        "type":"keyword"
                    },
                    "industry":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "asnumber":{
                        "type":"long"
                    },
                    "scene":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "city_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "user_type":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "district":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "country_code2":{
                        "ignore_above":32765,
                        "type":"keyword"
                    },
                    "country_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "dma_code":{
                        "type":"long"
                    },
                    "country_code3":{
                        "ignore_above":32765,
                        "type":"keyword"
                    },
                    "location":{
                        "type":"geo_point"
                    },
                    "region_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "real_region_name":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "timezone_utc":{
                        "ignore_above":32765,
                        "type":"keyword"
                    },
                    "postal_code":{
                        "ignore_above":32765,
                        "type":"keyword"
                    },
                    "user":{
                        "norms":false,
                        "type":"text",
                        "fields":{
                            "raw":{
                                "ignore_above":32765,
                                "type":"keyword"
                            }
                        }
                    },
                    "multiAreas":{
                        "dynamic":"true",
                        "properties":{
                            "lngbd":{
                                "type":"double"
                            },
                            "lngwgs":{
                                "type":"double"
                            },
                            "province":{
                                "type":"keyword"
                            },
                            "city":{
                                "type":"keyword"
                            },
                            "district":{
                                "type":"keyword"
                            },
                            "latwgs":{
                                "type":"double"
                            },
                            "radius":{
                                "type":"keyword"
                            },
                            "latbd":{
                                "type":"double"
                            }
                        }
                    },
                    "longitude":{
                        "type":"double"
                    }
                }
            },
            "honeypot_name":{
                "norms":false,
                "type":"text",
                "fields":{
                    "raw":{
                        "ignore_above":32765,
                        "type":"keyword"
                    }
                }
            },
            "type":{
                "type":"keyword"
            }
        }
    }
}`

func TestGetMappingTree(t *testing.T) {
	mapping := make(map[string]interface{})
	err := json.Unmarshal([]byte(mappingStr), &mapping)
	if err != nil {
		t.Fatal(err)
	}
	tree := GetMappingTree(mapping)
	t.Log(tree)
	marshal, err := json.Marshal(tree)
	if err != nil {
		return
	}
	t.Log(string(marshal))
}
