basePath: /api/v1
definitions:
  dto.UserLoginParam:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  resp.Response:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      message:
        description: 消息
        type: string
      requestID:
        type: string
    type: object
host: localhost:8070
info:
  contact: {}
  description: ddCode-server
  title: ddCode-server
  version: "1.0"
paths:
  /user/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.Response'
      summary: 用户登录
      tags:
      - 用户
swagger: "2.0"
